
spring:
  datasource:
    # url: ${SPRING_DATASOURCE_URL}
    # username: ${SPRING_DATASOURCE_USERNAME}
    # password: ${SPRING_DATASOURCE_PASSWORD}
    url: jdbc:mysql://localhost:3306/capstonedb
    username: root
    password: root
  jpa: 
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update