services:
  app:
    build: .
    ports: 
      - 8080:8080
    environment: 
      - 'SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/capstonedb?autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false'
      - 'SPRING_DATASOURCE_USERNAME=root'
      - 'SPRING_DATASOURCE_PASSWORD=root'
    depends_on:
      - mysql

  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=capstonedb'
      - 'MYSQL_PASSWORD=root'
      - 'MYSQL_ROOT_PASSWORD=root'
      - 'MYSQL_USER=root'
    ports:
      - '3306'